
# user_api:
#     type: rest
#     # resource: apibundle.controller.user
#     resource: '@ApiBundle/Controller/UserController.php'
#     # defaults: { _controller: ApiBundle:User:cget }
#     pattern:  /user

