# services:
#    api.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]


services:
    apibundle.controller.user:
        class: ApiBundle\Controller\UserController
        arguments: [@doctrine.orm.entity_manager, @apibundle.repo.user, @form.factory, @router]
    apibundle.controller.user:
        class: ApiBundle\Controller\UserController
        arguments: [@doctrine.orm.entity_manager, @apibundle.repo.user, @form.factory, @router]

    apibundle.repo.user:
        class: ApiBundle\Entity\UserRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - ApiBundle\Entity\User
    apibundle.repo.user:
        class: ApiBundle\Entity\UserRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - ApiBundle\Entity\User
